### ISSUE TITLE
Move the series parser into a separate file and class

### ISSUE THREAD

**Issue by Robson** [Robson/Yogscast-YouTube-Statistics#4]
It's currently here:

https://github.com/Robson/Yogscast-YouTube-Statistics/blob/main/GetYouTubeChannelStatistics/Program.cs#L114

**Comment by pghdeveloper** [comment]
@Robson I could work on this, but have you considered moving this to .Net Core?

**Comment by Robson** [comment]
That's a great idea - I've been meaning to try the Core version and this seems like an ideal opportunity. I'll do that next week, along with this task. Thank you for the suggestion!

**Comment by Robson** [comment]
This task is done ✔️
